config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: %i[show index new create edit update destroy]
  get 'signup', to: 'users#new'
  resources :users, except: %i[new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user # foreign key field (many articles to one user)
  
  has_many :article_categories # many articles to many categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 10, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 100 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 125 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    # methods defined here are available for use throughout the application

    helper_method :current_user, :logged_in?


    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:notice] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # instruct set_article() method to be called before the listed 'only' methods
  before_action :set_article, only: %i[edit update show destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]

  def show; end

  def index
    # paginated article
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # instantiate an new and empty article instance
  def new
    @article = Article.new
  end

  # recieves POST request from /new and persists the database with recieved data
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      flash[:notice] = 'Article was successfully created.'
      redirect_to action: 'show', id: @article.id
    else
      render 'new'
    end
  end

  def edit; end

  # recieves POST request from /edit and update instance the database with recieved data
  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated to: #{@article.title}"
      redirect_to @article
    else
      render 'edit'
    end
  end

  # recieves DELETE request with article id and deletes its instance from database
  def destroy
    if @article.destroy
      flash[:notice] = 'Article was successfully deleted.'
      redirect_to articles_path
    else
      flash[:error] = 'Something went wrong'
      redirect_to 'home'
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end
  def article_params
    params.require(:article).permit(:title, :description, category_ids:[])
  end

  def require_same_user
    if @article.user != current_user
      flash[:error] = "Only article owner can perform this operation."
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    
    def index
      @categories = Category.paginate(page: params[:page], per_page: 5)
    end
    
    def new
      @category = Category.new
    end
    
    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:notice] = "Category was created successfully"
        redirect_to @category
      else
        render 'new'
      end
    end
    
    def edit
      @category = Category.find(params[:id])
    end
    
    def update
      @category = Category.find(params[:id])
      if @category.update(category_params)
        flash[:notice] = "Category name was updated successfully"
        redirect_to category_path(@category)
      else
        render 'edit'
      end
    end
    
    def show
      @category = Category.find(params[:id])
      @articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end
    
    private
    
    def category_params
      params.require(:category).permit(:name)
    end
    
    def require_admin
      if !logged_in? || (logged_in? && !current_user.admin?)
        flash[:error] = "Only admins can perform that action"
        redirect_to categories_path
      end
    end
    
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home()
    redirect_to articles_path if logged_in?
  end
  
  def about(); end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  # login and add user_id to session
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully'
      redirect_to user
    else
      flash.now[:error] = 'There was a problem signing you in. Please try again'
      render 'new'
    end
  end
  # remove user id from session
  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_user, only: %i[edit update]
  before_action :same_user, only: %i[edit update destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Account was successfully created.'
      redirect_to action: 'show', id: @user.id
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'User account was successfully updated'
      redirect_to @user
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if !current_user.admin?
    flash[:notice] = "Accounts and associated posts deleted. We'll miss you."
    redirect_to root_path
  end
  
  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def same_user
    if @user != current_user && !current_user.admin?
      flash[:error] = "Your can only edit your own profile."
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user)
        email_address = user.email.downcase
        hash=Digest::MD5.hexdigest(email_address)
        image_src="https://www.gravatar.com/avatar/#{hash}?s=200"
        image_tag(image_src, alt:user.username, class:"rounded mx-auto d-block mb-5")
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.erb
<div class="container">
    <% @articles.each do |article| %>
        <div class="card shadow rounded mb-5 text-center">  
            <div class="card-header">
                by <%= link_to article.user.username, user_path(article.user),class:"text-success" %>
            </div>

            <div class="card-body">
                <h5 class="card-title"> <%= link_to article.title,article_path(article), class:"text-success"%> <br></h5>
                <p class="card-text"> <%= truncate(article.description, length: 100) %></p>
                <%= link_to 'View', article_path(article), class: "btn btn-outline-success" %>
                
                <% if logged_in? and (article.user==current_user || current_user.admin ) %>
                    <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-warning" %>
                    <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-outline-danger" %>
                <% end %>
            </div>
            <div class="card-footer text-muted">
                <p>
                    created: <%= time_ago_in_words(article.created_at) %> |
                    Last updated: <%= time_ago_in_words(article.updated_at) %>
                </p>
            </div>
        </div>
    <% end %> 

</div>

<% if logged_in? %>
    <div class="container-fluid text-center justify-content-md-center">
        <div class="row">
            <div class="col-md-12">
                <%= link_to  "Create new article", new_article_path, class: "btn btn-warning mb-5" %>
            </div>
        </div>
    </div>
<% end %>

app/views/articles/_form.erb
<div class="container">
    <div class="row justify-content-center">
        
        <div class="col-10">
            <%= render 'shared/errors', obj:@article %>
            <%= form_with(model: @article,class:"shadow rounded p-5 bg-success", local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :title, class:"col-2 text-white" %>
                    <div class="col-10">
                        <%= f.text_field :title, class:"form-control shadow rounded", placeholder: "Title of Article" %>        
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :description,class:"col-2 text-white " %>
                    <div class="col-10">
                        <%= f.text_area :description, row:10,class:"form-control shadow rounded", placeholder: "Description of Article" %>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :category,class:"col-2 text-white " %>
                    <div class="col-10">
                       <%= f.collection_select(:category_ids,Category.all, :id, :name,{ prompt: "Choose categories below (can be empty"}, {multiple: true, class: "custom-select shadow rounded" }) %>
                        <%# <%= f.text_area :description, row:10,class:"form-control shadow rounded", placeholder: "Description of Article" %> 
                    </div>
                </div>
                <div class="form-group row justify-content-center">
                    <%= f.submit class:"mt-5 btn btn-outline-dark text-white" %>
                </div>
            <% end %>
        </div>
        
        <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]      
        </div>
    </div>
</div>

app/views/articles/edit.erb
<h1 class="text-center mb-5">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.erb
<h1 class="text-center mb-5">All articles</h1>

<div class="flickr_pagination">
    <div class="page_info">
        <%= will_paginate @articles %>
    </div>
</div>
<%= render 'articles' %>
<div class="flickr_pagination mb-4">
    <div class="page_info">
        <%= will_paginate @articles %>
    </div>
</div>

app/views/articles/new.erb
<h1 class="text-center mb-5">Add new article</h1>
<%= render 'form' %>

app/views/articles/show.erb
<h1 class="text-center mb-5">Showing articles details</h1>
  <div class="container">
        <div class="card shadow rounded mb-5 text-center">  
        <div class="card-header">
          by <%= link_to @article.user.username, user_path(@article.user),class:"text-success" %>
        </div>

        <div class="card-body">
            <h5 class="card-title text-success "> <%= @article.title %> </h5>
            <%= gravatar_for(@article.user) %>
            <p class="card-text"> <%= simple_format(@article.description) %></p>
            <% if logged_in? and (@article.user==current_user || current_user.admin ) %>
                <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-warning" %>
                <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-outline-danger" %>
            <% end %>
        </div>
        <div class="card-footer text-muted">
            <p>
                created: <%= time_ago_in_words(@article.created_at) %> |
                Last updated: <%= time_ago_in_words(@article.updated_at) %>
            </p>
        </div>
        </div>
  </div>
  
  <div class="container-fluid text-center justify-content-md-center">
      <div class="row">
          <div class="col-md-12">
            <%= link_to 'Return to listing', articles_path %> 
          </div>
      </div>
  </div>

app/views/categories/_categories.erb
<div class="container">
    <% @categories.each do |category| %>
    <div class="card shadow rounded mb-5 text-center">  
        <div class="card-body">
            <h5 class="card-title"> <%= link_to category.name,category_path(category), class:"text-success"%> <br></h5>
            Articles count: <%= category.articles.count %>
        </div>
        <div class="card-footer text-muted">
            <small>
                created: <%= time_ago_in_words(category.created_at) %> |
            </small>
        </div>
    </div>
    <% end %> 

</div>

app/views/categories/_form.erb
<div class="container">
    <div class="row justify-content-center">
        
        <div class="col-10">
            <%= render 'shared/errors', obj:@category %>
            <%= form_with(model: @category,class:"shadow rounded p-5 bg-success", local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :name,"Category name", class:"col-2 text-white" %>
                    <div class="col-10">
                        <%= f.text_field :name, class:"form-control shadow rounded", placeholder: "Title of Article" %>        
                    </div>
                </div>
                <div class="form-group row justify-content-center">
                    <%= f.submit class:"mt-5 btn btn-outline-dark text-white" %>
                </div>
            <% end %>
        </div>
        
        <div class="col-xs-4 col-xs-offset-4 mt-3">
            [ <%= link_to "Cancel request and return to categories listing", categories_path %> ]      
        </div>
    </div>
</div>

app/views/categories/edit.erb
<h1 class="text-center mb-5">Edit category</h1>
<%= render 'form' %>

app/views/categories/index.erb
<h1 class="text-center mb-5">All Categories</h1>

<div class="flickr_pagination">
    <div class="page_info">
        <%= will_paginate @categories %>
    </div>
</div>
<%= render 'categories' %>
<div class="flickr_pagination mb-4">
    <div class="page_info">
        <%= will_paginate @categories %>
    </div>
</div>

app/views/categories/new.erb
<h1 class="text-center mb-5">Add new category</h1>
<%= render 'form' %>

app/views/categories/show.erb
<h1 class="text-center mb-5"> Category: <%= @category.name %> </h1>

<div class="container">

    <% if logged_in? && current_user.admin? %>
        <div class="text-center mb-4">
            <%= link_to 'Edit category name', edit_category_path(@category), class: "btn btn-outline-primary" %>   
        </div>
    <% end %>

    <h2 class="text-center mb-5"> Articles </h2>

    <div class="flickr_pagination mb-4">
        <div class="page_info">
            <%= will_paginate @articles, :container=> false %>
        </div>
    </div>

    <%= render 'articles/articles' %>

    <div class="flickr_pagination mb-4">
        <div class="page_info">
            <%= will_paginate @articles, :container=> false%>
        </div>
    </div>
</div>

app/views/layouts/_footer.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
        <small>
            Copyright &copy; Your website
        </small>
    </div>
</footer>

app/views/layouts/_messages.erb
  <% flash.each do |name,msg| %>
    <div class="alert alert-<%= name=='notice'? 'success': 'danger' %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

app/views/layouts/_nav.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "About", about_path, class: "nav-link"%>

        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Articles
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'All articles', articles_path, class: "dropdown-item" %>
            
            <% if logged_in? %>
              <%= link_to 'Create Article', new_article_path, class: "dropdown-item" %>
            <% end %>
            
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Categories', categories_path, class: "dropdown-item" %>
            
            <% if logged_in? %>
              <%= link_to 'Create new category', new_category_path, class: "dropdown-item" %>
            <% end %>
            
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link"%>
        </li>

        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile: <%= current_user.username %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'View profile', user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Edit profile', edit_user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: 'Are you sure?'} %>
          </div>
        </li>
        <% end %>

        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
          </li>
        <% else  %>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link"%>
          </li>  
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link"%>
          </li>      
        <% end %>
        
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/nav' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.erb
<h1>Na the about page be this </h1>

app/views/pages/home.erb
<div class="container-fluid text-center" id="home-container">
    <div class="jumbotron home-jumbotron">
        <h1 class="display-4"> Alpha blog </h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg"%>

    </div>
</div>

app/views/shared/_errors.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">
            Errors encountered
        </h4>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end  %>
        </ul>
         <button type="button" class="close" data-dismiss="alert" aria-label="Close">
         <span aria-hidden="true">&times;</span>
         </button>
    </div>
<% end %>

app/views/users/_form.erb
<div class="container">
    <div class="row justify-content-center">
        
        <div class="col-10">
            <%= render 'shared/errors', obj: @user %>
            <%= form_with(model: @user,class:"shadow rounded p-5 bg-success", local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :username, class:"col-2 text-white" %>
                    <div class="col-10">
                        <%= f.text_field :username, class:"form-control shadow rounded", placeholder: "Enter username" %>        
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :email,class:"col-2 text-white " %>
                    <div class="col-10">
                        <%= f.email_field :email,class:"form-control shadow rounded", placeholder: "Enter your email" %>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :password,class:"col-2 text-white " %>
                    <div class="col-10">
                        <%= f.password_field :password, class:"form-control shadow rounded", placeholder: "Enter password" %>
                    </div>
                </div>
                <div class="form-group row justify-content-center">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class:"mt-5 btn btn-outline-dark text-white") %>
                </div>
            <% end %>
        </div>
        
        <div class="col-xs-4 col-xs-offset-4">    
        </div>
    </div>
</div>

app/views/users/edit.erb
<h1 class="text-center mt-4">Edit user details </h1>
<%= render 'form' %>

app/views/users/index.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>
<div class="container">
    
    <div class="flickr_pagination">
        <div class="page_info">
            <%= will_paginate @users %>
        </div>
    </div>
    
    <% @users.each do |user| %>
    <div class="card shadow rounded mb-5 text-center">  
    <div class="card-header">
        <%= user.username %>
    </div>

    <div class="card-body">
        <%= gravatar_for(user) %>
        <p>
            Articles count: <%= user.articles.count %>
        </p>
        <%= link_to 'View profile', user_path(user), class: "btn btn-outline-success" %>
        <% if logged_in? %>
            <% if user==current_user %>
                <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-warning" %>
            <% end %>
        
            <% if current_user.admin? %>
                <%= link_to 'Delete profile', user_path(user), class: "btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            
        <% end %>
        
    </div>
    
    <div class="card-footer text-muted">
        <p>
            Joined <%= time_ago_in_words(user.created_at) %> ago
        </p>
    </div>
    </div>
    <% end %> 

    <div class="flickr_pagination">
        <div class="page_info">
            <%= will_paginate @users %>
        </div>
    </div>
</div>

app/views/users/new.erb
<h1 class="text-center mt-4">User sign up </h1>
<%= render 'form' %>

app/views/users/show.erb
<h1 class="text-center mb-5"> <%= @user.username %>'s profile</h1>
<%= gravatar_for(@user)%>

<% if logged_in? and (@user==current_user || current_user.admin ) %>
    <div class="text-center mt-4">
        <%= link_to "Edit profile",edit_user_path(@user), class:"btn btn-outline-success" %>
    </div>
<% end %>
<h1 class="text-center mb-5"> <%= @user.username %>'s articles</h1>

<div class="flickr_pagination mb-4">
    <div class="page_info">
        <%= will_paginate @articles, :container=> false %>
    </div>
</div>

<%= render 'articles/articles' %>

<div class="flickr_pagination mb-4">
    <div class="page_info">
        <%= will_paginate @articles, :container=> false%>
    </div>
</div>